### PR TITLE
GSAGH-535 Add Truss GsaGH demo file to oasys-sample-files repo

### PR DESCRIPTION
**Pull request by Abishek20Feb**
Adding truss model with displacement results in 1D contour and text output to Oasys-sample-files

### CODE REVIEW

**Review by KarthikAppakutti — CHANGES_REQUESTED** [review]
As discussed, please name the components or group of components (like, Length of the Truss, number of segments, chord member and braces)

**Review by PeterDebneyOasys — CHANGES_REQUESTED** [review]
I note that the diagonals are all Beam elements, giving them induced moments.
Can we add releases onto the ends of the small members to release the moments, but not so many that the truss is destabalised

**Review by KarthikAppakutti — DISMISSED** [review]

**Review by PeterDebneyOasys — CHANGES_REQUESTED** [review]
If the Segment slider is set to a value 8 or more then the truss stops analysing - all the diagonals in the 8th segment and beyond connect to the wrong node.

I note that most of the user-defined parameters are highlighted with a Group and Text.
Please can you add this to the Span to Depth ratio slider and also rename it from "B"

This is a personal preference, but I find it useful to have all the slider controls in the same place, so that you / the user can easily find and adjust the model with them without moving around the GH interface

**Comment by Abishek20Feb** [comment]
The number of segments can be increased now without any issue in the model, and the inputs are grouped in the same place with proper naming for height, length, and spacing of trusses. 
I have added a panel showing span to depth ratio in addition.

**Review by PeterDebneyOasys — APPROVED** [review]
Looks OK to me

**Pull request merged**
